version: '3.8'

services:
  # Backend - PHP
  php:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: base-fpm
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - database
    environment:
      #- DATABASE_URL=mysql://app:!ChangeMe!@database:3336/app?serverVersion=8.0.33&charset=utf8mb4
      - DATABASE_URL=mysql://app:!ChangeMe!@database:3306/app?serverVersion=8.0.33&charset=utf8mb4
      - MAILER_DSN=smtp://mailhog:1025
      - APP_ENV=dev
      - APP_SECRET=123456789

  # Backend - Nginx
  nginx:
    image: nginx:alpine
    ports:
      - "8002:80"
    volumes:
      - ./backend:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  # Database
  database:
    image: mysql:8.0.33
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: '!ChangeMe!'
      MYSQL_ROOT_PASSWORD: '!ChangeMe!'
    volumes:
      - database_data:/var/lib/mysql
    ports:
      - "3336:3306"

  # Frontend - React
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3002:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8002/api

volumes:
  database_data: 